version: '2'

services:
  main:
    build: ./src
    volumes:
      - ./src:/var/log/erss
    ports:
      - "12345:12345"
  flask:
    build: ./flask_app
    volumes:
      - ./src:/app/file
    ports:
      - "5000:5000" 